[project]
name = "mlip-struc-gen-local"
version = "0.1.0"
description = "MACE-based structure optimization pipeline"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0.0",
    "torchvision",
    "mace-torch>=0.3.4",
    "ase>=3.23.0",
    "pydantic>=2.0",
    "pydantic-settings",
    "loguru",
    "numpy",
    "scipy",
    "hydra-core",
    "omegaconf",
    "pymatgen",
    "python-dotenv",
    "pyxtal",
    "param",
    "panel",
    "pytest",
    "pytest-mock"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
